name: Build for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install mingw for cross-compiling
        run: |
          sudo apt update
          sudo apt install -y mingw-w64

      - name: Build project for ${{ matrix.target }}
        run: cargo build --release --target=${{ matrix.target }}
